name: uber
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  sizer: ^2.0.15
  country_picker: ^2.0.20
  flutter_svg: ^2.0.5
  pin_code_fields: ^8.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  provider: ^6.1.1
  page_transition: ^2.1.0
  firebase_database: ^10.3.8
  file_picker: ^5.3.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  flutter_styled_toast: ^2.1.3
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  uuid: ^4.1.0
  image_picker: ^1.0.4
  connectivity: ^3.0.6
  google_maps_flutter: ^2.3.0
  intl: ^0.17.0
  shimmer: ^3.0.0
  geolocator: ^10.1.0
  sliding_up_panel: ^2.0.0+1
  http: ^0.13.6
  flutter_polyline_points: ^1.0.0
  flutter_swipe_button: ^2.1.1+1
  flutter_geofire: ^2.0.3
  firebase_messaging: ^14.7.9
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/authIcons/
    - assets/images/uberLogo/
    - assets/images/suggestions/
    - assets/images/promotion/
    - assets/images/moreWaysUber/
    - assets/images/planNextTrip/
    - assets/images/saveEveryDay/
    - assets/images/services/
    - assets/images/vehicle/
    - assets/images/icons/
    - assets/sounds/
    - assets/json/customizedMap.json

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
